#开发环境
text: 这里是开发环境

#mysql数据源配置
spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.zhangxuxiang.cn:13306/recommender?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: Zxx123456
    dbcp2:
      initial-size: 5
      min-idle: 5
    tomcat:
      max-active: 30



---
# 自动将数据库下划线字段转成java驼峰

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#分页插件配置

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true


#日志级别 trace<debug<info<warn<error<fatal,默认级别为info，即默认打印info及其以上级别的日志

logging:
  level:
    cn:
      zxx: debug
    org:
      springframework:
        data:
          convert:
            CustomConversions: ERROR

---
#官方驱动neo4j数据源配置

spring:
  neo4j:
    url: neo4j://localhost:7687
    user: neo4j
    password: js20030320
---
#集成驱动neo4j数据源配置
spring:
  data:
    neo4j:
      uri:neo4j://localhost:7687
      username:neo4j
      password:js20030320

#服务端口
#应用上下文
server:
  port: 8080
  servlet:
    context-path: /


---
#为引入swagger生成api文档,更改默认路径匹配策略为AntPathMatcher

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtps
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 19308484968@163.com
    #授权码
    password: OQWNBQUJATYYEHID
    #端口465或587
    port: 465